project:
  type: website
  render: 
    - "*.qmd"

execute: 
  freeze: auto
  
website:
  title: "UP 510: Plan Making - Teutopolis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: syllabus/syllabus.qmd
        text: "Syllabus"
      - href: deliverables/deliverables.qmd
        text: "Milestones"
      - href: schedule/schedule.qmd
        text: "Schedule"
    search: true
  favicon: favicon.png
  page-footer:
    left: "Content {{< fa regular copyright >}} Andrew J. Greenlee"
    right: "Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) </br> Website Code on [Github {{< fa brands github >}}]({{< var course.github >}})"

  sidebar:
    - title: "Schedule"
      style: "docked"
      contents:
        - section: "Schedule"
          contents:
            - text: "Schedule Overview"
              file: schedule/schedule.qmd
            - text: "Week 1: Seminar Introduction"
              file: schedule/01_Introduction.qmd
            - text: "Week 2: Defining Your Capstone"
              file: schedule/02_Defining.qmd
            - text: "Week 3: Defining Outputs"
              file: schedule/03_Outputs.qmd
            - text: "Week 4: Developing Your 2-Year Professional Development Plan"
              file: schedule/04_DevelopmentPlan.qmd
            - text: "Week 5: 	No Class - APA-IL Conference"
            - text: "Week 6: Defining a Plan Ecosystem"
              file: schedule/06_PlanEcosystem.qmd
            - text: "Week 7: Methods"
              file: schedule/07_Methods.qmd
            - text: "Week 8: Independent Work - No Class"
            - text: "Week 9: Developing a Professional Portfolio - Session 1"
              file: schedule/09_Portfolio1.qmd
            - text: "Week 10: Participation and Stakeholder Engagement"
              file: schedule/10_Participation.qmd
            - text: "Week 11: Independent Work - No Class"
            - text: "Week 12: Writing Skills"
              file: schedule/12_WritingSkills.qmd
            - text: "Week 13: Developing a Professional Portfolio - Session 2"
              file: schedule/13_Portfolio2.qmd
            - text: "Week 14: Fall Break - No Class"    
            - text: "Week 15: End of Semester Check-In"
              file: schedule/15_CheckIn.qmd
            
    - title: "Deliverables"
      style: "docked"
      contents:
        - section: "Deliverables Overview"
          contents:
            - text: "Plan of Study Update"
              file: schedule/01_planofstudy.qmd

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: darkly
    css: 
      - styles.css
    toc: true

editor: source

